pipeline {
  agent any
  stages {
    stage('阶段 1-1') {
      steps {
        checkout([
          $class: 'GitSCM',
          branches: [[name: env.GIT_BUILD_REF]],
          userRemoteConfigs: [[
            url: env.GIT_REPO_URL,
            credentialsId: env.CREDENTIALS_ID
          ]]])
        }
      }
      stage('阶段 2-1') {
        steps {
          sh '''curl -u pton3jowzj5o:38a2218f618e6be13d5b3c1e871f70a1621ea302 \\
-v -X POST  \'https://dai-test.coding.net/api/cci/job/849989/trigger\' \\
-H \'Content-Type: application/json\' \\
-d \'
{
"ref": "master",
"envs": [
{
"name": "test",
"value": '$new',
"sensitive": 0
}
]
}\''''
        }
      }
    }
  }